// Builds assets/osap-milsym-cat.js: the searchable list of MIL-STD-2525D (change 1) symbol functions that the map
// point icon picker (assets/osap-milsym.js) offers. Names come from the TSV tables in the mil-std-2525 package (MIT,
// https://github.com/spatialillusions/mil-std-2525); every entry is kept only when milsymbol (MIT) can draw it.
//
//   npm install --no-save milsymbol@3.0.4 mil-std-2525@0.2.8
//   node tools/build_milsym_catalog.mjs
//
// Output: window.OSAP_MSCAT = { std, order: [set codes in picker order], sets: {code: [name, domain]}, e: {set: [[entity, name, path]]}, m1: {set: [[code, name]]}, m2: ... }
import fs from "fs";
import path from "path";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const ms = require(process.env.MILSYMBOL || "milsymbol");
const TSV = process.env.MSTD_TSV || path.join(path.dirname(require.resolve("mil-std-2525/package.json")), "tsv-tables", "2525d");

// symbol set code -> [table file, plain name, picker domain]
const SETS = {
  "10": ["Land unit", "Land unit", "land"],
  "11": ["Land civilian", "Land civilian", "land"],
  "15": ["Land equipment", "Land equipment", "land"],
  "20": ["Land installation", "Land installation", "land"],
  "52": ["Signals intelligence", "Land signals intelligence", "land"],
  "01": ["Air", "Air", "air"],
  "02": ["Air missile", "Air missile", "air"],
  "51": ["Signals intelligence", "Air signals intelligence", "air"],
  "30": ["Sea surface", "Sea surface", "sea"],
  "53": ["Signals intelligence", "Sea surface signals intelligence", "sea"],
  "35": ["Sea subsurface", "Subsurface", "sub"],
  "36": ["Mine warfare", "Mine warfare", "sub"],
  "54": ["Signals intelligence", "Subsurface signals intelligence", "sub"],
  "05": ["Space", "Space", "space"],
  "06": ["Space missile", "Space missile", "space"],
  "50": ["Signals intelligence", "Space signals intelligence", "space"],
  "40": ["Activities", "Activities and events", "act"],
  "25": ["Control Measures", "Map graphics (point)", "cm"],
  "60": ["Cyberspace", "Cyberspace", "cyber"]
};
function rows(file) {
  const f = path.join(TSV, file + ".tsv");
  if (!fs.existsSync(f)) return null;
  const L = fs.readFileSync(f, "utf8").split(/\r?\n/).filter((l) => l.trim());
  const head = L.shift().split("\t").map((s) => s.trim());
  return L.map((l) => { const c = l.split("\t"), o = {}; head.forEach((h, i) => { o[h] = (c[i] || "").trim(); }); return o; });
}
const clean = (s) => s.replace(/\s+/g, " ").replace(/\s*\/\s*/g, "/").trim();
function draws(sidc) { try { return new ms.Symbol(sidc, { size: 20 }).isValid(); } catch (e) { return false; } }

const out = { std: "MIL-STD-2525D change 1", order: [], sets: {}, e: {}, m1: {}, m2: {} };
let total = 0, dropped = 0;
// picker order (an object keeps "10" before "01", so the order is spelled out)
const ORDER = ["10", "11", "15", "20", "52", "01", "02", "51", "30", "53", "35", "36", "54", "05", "06", "50", "40", "25", "60"];
for (const set of ORDER) {
  const [file, name, dom] = SETS[set];
  const R = rows(file); if (!R) { console.warn("missing table " + file); continue; }
  out.sets[set] = [name, dom]; out.order.push(set);
  let ent = "", typ = "";
  const list = [];
  for (const r of R) {
    const code = (r.Code || "").replace(/\D/g, "");
    if (r.Entity) { ent = clean(r.Entity); typ = ""; }
    if (r["Entity Type"]) typ = clean(r["Entity Type"]);
    if (code.length !== 6 || code === "000000") continue;
    if (set === "25" && !/point/i.test(r["Geometric Rendering"] || "")) continue;
    const nm = clean(r["Entity Subtype"] || r["Entity Type"] || r.Entity);
    const trail = r["Entity Subtype"] ? [ent, typ] : r["Entity Type"] ? [ent] : [];
    if (!draws("1001" + set + "0000" + code + "0000")) { dropped++; continue; }
    list.push([code, nm, trail.filter(Boolean).join(" › ")]);
  }
  out.e[set] = list; total += list.length;
  for (const k of ["1", "2"]) {
    const M = rows(file + " sector " + k); if (!M) continue;
    const col = k === "1" ? "First Modifier" : "Second Modifier";
    const ml = M.map((r) => [(r.Code || "").replace(/\D/g, ""), clean(r[col] || "")]).filter((m) => m[0].length === 2 && m[0] !== "00" && m[1]);
    if (ml.length) out["m" + k][set] = ml;
  }
}
const dst = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "assets", "osap-milsym-cat.js");
fs.writeFileSync(dst, "/* generated by tools/build_milsym_catalog.mjs from mil-std-2525 (MIT) and checked with milsymbol 3.0.4 (MIT); do not edit by hand */\nwindow.OSAP_MSCAT = " + JSON.stringify(out) + ";\n");
console.log("wrote " + dst + ": " + total + " functions in " + Object.keys(out.e).length + " sets (" + dropped + " not drawable, left out), " + fs.statSync(dst).size + " bytes");
