// Builds the Country boundaries overlay (assets/osap-borders.js): every land border between countries, worldwide, as lines.
//   data/basemap/borders-50m.js  Natural Earth 1:50m, thinned to 0.01 degree, used when the map is zoomed out (below zoom 6)
//   data/basemap/borders-10m.js  Natural Earth 1:10m, thinned to 0.002 degree, used from zoom 6 in
// Both load only when the overlay is switched on (the 1:10m file only once the map is zoomed in), so they cost nothing at start.
// Source: Natural Earth admin-0 countries (public domain) from the world-atlas npm package; a border is a TopoJSON arc shared
// by two countries, so each border is one line (no doubled strokes) and coastlines are left to the base map. Lines follow
// Natural Earth's de facto boundaries; disputed borders are not marked as such.
//
//   npm install --no-save world-atlas@2.0.2 topojson-client@3     (or WORLD_ATLAS=/path/to/node_modules)
//   node tools/build_borders.mjs
//
// Each line is stored as integers in 1/100 (50m) or 1/1000 (10m) of a degree: the first point whole, then the change from the
// point before ([x0, y0, dx1, dy1, ...]), which keeps the files small. window.OSAP_BORDERS[res] = { s: scale, l: [lines] }.
import fs from "fs";
import path from "path";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const base = process.env.WORLD_ATLAS ? process.env.WORLD_ATLAS.replace(/\/$/, "") + "/" : "";
const tc = require(base + "topojson-client");

function dp(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const st = [[0, pts.length - 1]];
  while (st.length) {
    const [a, b] = st.pop(); let md = 0, mi = -1;
    const [x1, y1] = pts[a], [x2, y2] = pts[b], dx = x2 - x1, dy = y2 - y1, L = Math.hypot(dx, dy);
    for (let i = a + 1; i < b; i++) {
      const d = L ? Math.abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / L : Math.hypot(pts[i][0] - x1, pts[i][1] - y1);
      if (d > md) { md = d; mi = i; }
    }
    if (md > tol && mi > 0) { keep[mi] = 1; st.push([a, mi], [mi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const dir = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "data", "basemap");
for (const [res, tol, scale] of [["50m", 0.01, 100], ["10m", 0.002, 1000]]) {
  const topo = require(base + "world-atlas/countries-" + res + ".json");
  const mesh = tc.mesh(topo, topo.objects.countries, (a, b) => a !== b);
  let pts = 0;
  const lines = mesh.coordinates.map((l) => {
    const q = [];
    for (const [x, y] of dp(l, tol)) {
      const p = [Math.round(x * scale), Math.round(y * scale)], last = q[q.length - 1];
      if (!last || last[0] !== p[0] || last[1] !== p[1]) q.push(p);
    }
    return q;
  }).filter((q) => q.length >= 2).map((q) => {
    pts += q.length;
    const out = [q[0][0], q[0][1]];
    for (let i = 1; i < q.length; i++) out.push(q[i][0] - q[i - 1][0], q[i][1] - q[i - 1][1]);
    return out;
  });
  const body = "/* generated by tools/build_borders.mjs from Natural Earth 1:" + res + " admin-0 countries (public domain); do not edit by hand */\n" +
    "(window.OSAP_BORDERS=window.OSAP_BORDERS||{})[\"" + res + "\"]=" + JSON.stringify({ s: scale, l: lines }) + ";\n";
  const dest = path.join(dir, "borders-" + res + ".js");
  fs.writeFileSync(dest, body);
  console.log("wrote", dest, body.length, "bytes,", lines.length, "lines,", pts, "points");
}
