// Builds data/basemap/sides-full.js: whole outlines of the countries that data/basemap/country-outlines.js clips to the
// Asia-Pacific (the United States there is only the western Aleutians, Russia only its Far East), so that Country sides
// (assets/osap-sides.js) can tint the whole country. Loaded by the page only when one of these countries is marked.
// Source: Natural Earth 1:50m (public domain) from the world-atlas npm package.
//
//   npm install --no-save world-atlas@2.0.2 topojson-client@3     (or WORLD_ATLAS=/path/to/node_modules)
//   node tools/build_sides_outlines.mjs
//
// Coordinates are rounded to 0.01 degree like the other outline files and thinned with Douglas-Peucker (0.02 degree).
// Russia, Fiji and Kiribati straddle the dateline; every point of theirs west of 0 is moved by +360 so each draws as one
// piece on OSAP's Pacific-centred map (the map pans to 240 degrees east). The United States is left as it is, so Alaska and
// Hawaii stay beside the rest of the country.
import fs from "fs";
import path from "path";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const base = process.env.WORLD_ATLAS ? process.env.WORLD_ATLAS.replace(/\/$/, "") + "/" : "";
const topo = require(base + "world-atlas/countries-50m.json"), tc = require(base + "topojson-client");

const WANT = ["United States of America", "Russia", "Fiji", "Kiribati"], SHIFT = { Russia: 1, Fiji: 1, Kiribati: 1 }, TOL = 0.02;
function dp(pts, tol) {
  if (pts.length < 5) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const st = [[0, pts.length - 1]];
  while (st.length) {
    const [a, b] = st.pop(); let md = 0, mi = -1;
    const [x1, y1] = pts[a], [x2, y2] = pts[b], dx = x2 - x1, dy = y2 - y1, L = Math.hypot(dx, dy) || 1e-12;
    for (let i = a + 1; i < b; i++) { const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / L; if (d > md) { md = d; mi = i; } }
    if (md > tol && mi > 0) { keep[mi] = 1; st.push([a, mi], [mi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
function ring(r, shift) {
  let out = [];
  for (const [x, y] of r) { const p = [+(x + (shift && x < 0 ? 360 : 0)).toFixed(2), +y.toFixed(2)]; const l = out[out.length - 1]; if (!l || l[0] !== p[0] || l[1] !== p[1]) out.push(p); }
  // a closed ring starts and ends on the same point, so thin its two halves, split at the point farthest from the start
  let far = 0, fd = -1;
  out.forEach((q, i) => { const d = Math.hypot(q[0] - out[0][0], q[1] - out[0][1]); if (d > fd) { fd = d; far = i; } });
  out = far > 0 ? dp(out.slice(0, far + 1), TOL).concat(dp(out.slice(far), TOL).slice(1)) : out;
  return out.length >= 4 ? out : null;
}
const fc = tc.feature(topo, topo.objects.countries), feats = [];
for (const n of WANT) {
  const f = fc.features.find((x) => x.properties.name === n);
  if (!f) throw new Error("not in Natural Earth: " + n);
  const polys = f.geometry.type === "Polygon" ? [f.geometry.coordinates] : f.geometry.coordinates, out = [];
  for (const p of polys) {
    const rs = p.map((r) => ring(r, !!SHIFT[n])); if (rs[0]) out.push(rs.filter(Boolean));
  }
  feats.push({ type: "Feature", properties: { n }, geometry: { type: "MultiPolygon", coordinates: out } });
}
const body = "/* generated by tools/build_sides_outlines.mjs from Natural Earth 1:50m (public domain); do not edit by hand */\n" +
  "window.OSAP_SIDES_FULL=" + JSON.stringify({ type: "FeatureCollection", features: feats }) + ";\n";
const dest = path.join(path.dirname(new URL(import.meta.url).pathname), "..", "data", "basemap", "sides-full.js");
fs.writeFileSync(dest, body);
console.log("wrote", dest, body.length, "bytes,", feats.length, "countries");
